# Generated by Django 3.2.24 on 2024-03-01 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_edited_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="ingredients",
            field=models.CharField(
                blank=True,
                help_text="List of ingredients, maximum 500 characters",
                max_length=500,
                verbose_name="ingredients",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                help_text="This will be displayed to the user as-is",
                max_length=150,
                unique=True,
                verbose_name="display name",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.PositiveSmallIntegerField(
                help_text="Price payable by the customer (Rs.)",
                verbose_name="selling price (Rs.)",
            ),
        ),
    ]
