# Generated by Django 3.2.24 on 2024-03-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_auto_20240301_0952"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="ingredients",
            field=models.CharField(
                blank=True,
                help_text="List of ingredients, maximum 500 characters",
                max_length=500,
                null=True,
                verbose_name="ingredients",
            ),
        ),
    ]
