# Generated by Django 3.2.24 on 2024-03-01 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_sku"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
    ]
