# Generated by Django 3.2.24 on 2024-03-01 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_remove_product_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sku",
            name="price",
        ),
        migrations.AddField(
            model_name="sku",
            name="cost_price",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sku",
            name="platform_commission",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sku",
            name="selling_price",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sku",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="products.product"
            ),
        ),
        migrations.AlterField(
            model_name="sku",
            name="size",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
