# Generated by Django 3.2.24 on 2024-03-01 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_auto_20240301_1115"),
    ]

    operations = []
