# Generated by Django 3.2.24 on 2024-03-01 12:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_auto_20240301_1201"),
    ]

    operations = [
        migrations.AddField(
            model_name="sku",
            name="measurement_unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("gm", "Gram"),
                    ("kg", "Kilogram"),
                    ("mL", "Milliliter"),
                    ("L", "Liter"),
                    ("pc", "Piece"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sku",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Pending for Approval"),
                    (1, "Approved"),
                    (2, "Discontinued"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="sku",
            name="size",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(999)],
            ),
        ),
    ]
